# Generated by Django 2.1.7 on 2019-06-04 08:46

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20190519_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='geo_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='photo',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8),
        ),
        migrations.AlterField(
            model_name='photo',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9),
        ),
    ]
